/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FhenixDropBox {
  export type UploadInputStruct = {
    ipfsHash: string;
    fileName: string;
    mimeType: string;
    fileSize: BigNumberish;
    price: BigNumberish;
    maxDownloads: BigNumberish;
    expiryDays: BigNumberish;
    accessCodeHash: BytesLike;
    contentEncrypted: boolean;
    encryptionKeyHash: BytesLike;
    folderId: BigNumberish;
    previewEnabled: boolean;
    previewHash: string;
    anonymousUpload: boolean;
  };

  export type UploadInputStructOutput = [
    ipfsHash: string,
    fileName: string,
    mimeType: string,
    fileSize: bigint,
    price: bigint,
    maxDownloads: bigint,
    expiryDays: bigint,
    accessCodeHash: string,
    contentEncrypted: boolean,
    encryptionKeyHash: string,
    folderId: bigint,
    previewEnabled: boolean,
    previewHash: string,
    anonymousUpload: boolean
  ] & {
    ipfsHash: string;
    fileName: string;
    mimeType: string;
    fileSize: bigint;
    price: bigint;
    maxDownloads: bigint;
    expiryDays: bigint;
    accessCodeHash: string;
    contentEncrypted: boolean;
    encryptionKeyHash: string;
    folderId: bigint;
    previewEnabled: boolean;
    previewHash: string;
    anonymousUpload: boolean;
  };
}

export interface FhenixDropBoxInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_BATCH_SIZE"
      | "MAX_PRICE"
      | "authorizedUsers"
      | "batchDownloadFiles"
      | "createFolder"
      | "deactivateFile"
      | "downloadFile"
      | "downloadHistory"
      | "files"
      | "folders"
      | "getAccessInfo"
      | "getBalance"
      | "getEncryptionInfo"
      | "getFileExpiry"
      | "getFileInfo"
      | "getFileMetadata"
      | "getFileOwner"
      | "getFilePrivacy"
      | "getFilesByFolder"
      | "getLatestFileId"
      | "getMyFiles"
      | "getMyFolders"
      | "getMyWebhooks"
      | "getRemainingDownloads"
      | "getStats"
      | "isFileExpired"
      | "moveFileToFolder"
      | "owner"
      | "reactivateFile"
      | "registerWebhook"
      | "renounceOwnership"
      | "requestAccess"
      | "revokeAccess"
      | "totalDownloads"
      | "totalFiles"
      | "totalFolders"
      | "totalVolume"
      | "totalWebhooks"
      | "transferOwnership"
      | "updateFileMetadata"
      | "updateFilePrivacy"
      | "updateFileRules"
      | "updateFolder"
      | "updateWebhook"
      | "uploadFile"
      | "uploadFileDetailed"
      | "uploadFilesBatch"
      | "userFiles"
      | "userFolders"
      | "userWebhooks"
      | "webhooks"
      | "withdraw"
      | "withdrawERC20"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessRevoked"
      | "BatchDownloaded"
      | "FileAccessed"
      | "FileDeactivated"
      | "FileDownloaded"
      | "FileMetadataUpdated"
      | "FileMoved"
      | "FilePrivacyUpdated"
      | "FileReactivated"
      | "FileRulesUpdated"
      | "FileUploaded"
      | "FolderCreated"
      | "FolderUpdated"
      | "OwnershipTransferred"
      | "WebhookRegistered"
      | "WebhookUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_PRICE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorizedUsers",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchDownloadFiles",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createFolder",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateFile",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "downloadFile",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "downloadHistory",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "files", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "folders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptionInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFileExpiry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFileInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFileMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFileOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFilePrivacy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFilesByFolder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestFileId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyFiles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyFolders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyWebhooks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingDownloads",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isFileExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moveFileToFolder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactivateFile",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerWebhook",
    values: [BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestAccess",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDownloads",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFiles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFolders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalWebhooks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFileMetadata",
    values: [BigNumberish, string, string, BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFilePrivacy",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFileRules",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFolder",
    values: [BigNumberish, string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWebhook",
    values: [BigNumberish, BytesLike, string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadFile",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      boolean,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadFileDetailed",
    values: [FhenixDropBox.UploadInputStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadFilesBatch",
    values: [FhenixDropBox.UploadInputStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "userFiles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userFolders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userWebhooks",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "webhooks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawERC20",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_PRICE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchDownloadFiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createFolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateFile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "downloadFile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "downloadHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "files", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "folders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccessInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFileExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFileInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFileMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFileOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFilePrivacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFilesByFolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestFileId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMyFiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMyFolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyWebhooks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingDownloads",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isFileExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moveFileToFolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateFile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerWebhook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDownloads",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalFiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalFolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWebhooks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFileMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFilePrivacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFileRules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWebhook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uploadFile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uploadFileDetailed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploadFilesBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userFiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userFolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userWebhooks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "webhooks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC20",
    data: BytesLike
  ): Result;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [fileId: BigNumberish, user: AddressLike];
  export type OutputTuple = [fileId: bigint, user: string];
  export interface OutputObject {
    fileId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchDownloadedEvent {
  export type InputTuple = [downloader: AddressLike, fileIds: BigNumberish[]];
  export type OutputTuple = [downloader: string, fileIds: bigint[]];
  export interface OutputObject {
    downloader: string;
    fileIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileAccessedEvent {
  export type InputTuple = [
    fileId: BigNumberish,
    requester: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [fileId: bigint, requester: string, price: bigint];
  export interface OutputObject {
    fileId: bigint;
    requester: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileDeactivatedEvent {
  export type InputTuple = [fileId: BigNumberish];
  export type OutputTuple = [fileId: bigint];
  export interface OutputObject {
    fileId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileDownloadedEvent {
  export type InputTuple = [
    fileId: BigNumberish,
    downloader: AddressLike,
    owner: AddressLike
  ];
  export type OutputTuple = [fileId: bigint, downloader: string, owner: string];
  export interface OutputObject {
    fileId: bigint;
    downloader: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileMetadataUpdatedEvent {
  export type InputTuple = [
    fileId: BigNumberish,
    fileName: string,
    mimeType: string,
    folderId: BigNumberish,
    previewHash: string
  ];
  export type OutputTuple = [
    fileId: bigint,
    fileName: string,
    mimeType: string,
    folderId: bigint,
    previewHash: string
  ];
  export interface OutputObject {
    fileId: bigint;
    fileName: string;
    mimeType: string;
    folderId: bigint;
    previewHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileMovedEvent {
  export type InputTuple = [
    fileId: BigNumberish,
    oldFolderId: BigNumberish,
    newFolderId: BigNumberish
  ];
  export type OutputTuple = [
    fileId: bigint,
    oldFolderId: bigint,
    newFolderId: bigint
  ];
  export interface OutputObject {
    fileId: bigint;
    oldFolderId: bigint;
    newFolderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FilePrivacyUpdatedEvent {
  export type InputTuple = [fileId: BigNumberish, anonymousUpload: boolean];
  export type OutputTuple = [fileId: bigint, anonymousUpload: boolean];
  export interface OutputObject {
    fileId: bigint;
    anonymousUpload: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileReactivatedEvent {
  export type InputTuple = [fileId: BigNumberish];
  export type OutputTuple = [fileId: bigint];
  export interface OutputObject {
    fileId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileRulesUpdatedEvent {
  export type InputTuple = [
    fileId: BigNumberish,
    price: BigNumberish,
    maxDownloads: BigNumberish,
    expiresAt: BigNumberish,
    hasPassword: boolean
  ];
  export type OutputTuple = [
    fileId: bigint,
    price: bigint,
    maxDownloads: bigint,
    expiresAt: bigint,
    hasPassword: boolean
  ];
  export interface OutputObject {
    fileId: bigint;
    price: bigint;
    maxDownloads: bigint;
    expiresAt: bigint;
    hasPassword: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileUploadedEvent {
  export type InputTuple = [
    fileId: BigNumberish,
    owner: AddressLike,
    ipfsHash: string,
    fileName: string,
    folderId: BigNumberish,
    price: BigNumberish,
    hasPassword: boolean,
    contentEncrypted: boolean,
    previewHash: string,
    anonymousUpload: boolean
  ];
  export type OutputTuple = [
    fileId: bigint,
    owner: string,
    ipfsHash: string,
    fileName: string,
    folderId: bigint,
    price: bigint,
    hasPassword: boolean,
    contentEncrypted: boolean,
    previewHash: string,
    anonymousUpload: boolean
  ];
  export interface OutputObject {
    fileId: bigint;
    owner: string;
    ipfsHash: string;
    fileName: string;
    folderId: bigint;
    price: bigint;
    hasPassword: boolean;
    contentEncrypted: boolean;
    previewHash: string;
    anonymousUpload: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FolderCreatedEvent {
  export type InputTuple = [
    folderId: BigNumberish,
    owner: AddressLike,
    name: string,
    color: string
  ];
  export type OutputTuple = [
    folderId: bigint,
    owner: string,
    name: string,
    color: string
  ];
  export interface OutputObject {
    folderId: bigint;
    owner: string;
    name: string;
    color: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FolderUpdatedEvent {
  export type InputTuple = [
    folderId: BigNumberish,
    name: string,
    color: string,
    isActive: boolean
  ];
  export type OutputTuple = [
    folderId: bigint,
    name: string,
    color: string,
    isActive: boolean
  ];
  export interface OutputObject {
    folderId: bigint;
    name: string;
    color: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WebhookRegisteredEvent {
  export type InputTuple = [
    webhookId: BigNumberish,
    owner: AddressLike,
    endpointHash: BytesLike,
    eventMask: BigNumberish
  ];
  export type OutputTuple = [
    webhookId: bigint,
    owner: string,
    endpointHash: string,
    eventMask: bigint
  ];
  export interface OutputObject {
    webhookId: bigint;
    owner: string;
    endpointHash: string;
    eventMask: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WebhookUpdatedEvent {
  export type InputTuple = [
    webhookId: BigNumberish,
    endpointHash: BytesLike,
    eventMask: BigNumberish,
    isActive: boolean
  ];
  export type OutputTuple = [
    webhookId: bigint,
    endpointHash: string,
    eventMask: bigint,
    isActive: boolean
  ];
  export interface OutputObject {
    webhookId: bigint;
    endpointHash: string;
    eventMask: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FhenixDropBox extends BaseContract {
  connect(runner?: ContractRunner | null): FhenixDropBox;
  waitForDeployment(): Promise<this>;

  interface: FhenixDropBoxInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  MAX_PRICE: TypedContractMethod<[], [bigint], "view">;

  authorizedUsers: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  batchDownloadFiles: TypedContractMethod<
    [fileIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  createFolder: TypedContractMethod<
    [name: string, color: string],
    [bigint],
    "nonpayable"
  >;

  deactivateFile: TypedContractMethod<
    [fileId: BigNumberish],
    [void],
    "nonpayable"
  >;

  downloadFile: TypedContractMethod<
    [fileId: BigNumberish],
    [void],
    "nonpayable"
  >;

  downloadHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  files: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean,
        string,
        bigint,
        boolean,
        string,
        boolean
      ] & {
        ipfsHash: string;
        fileName: string;
        mimeType: string;
        fileSize: bigint;
        createdAt: bigint;
        price: bigint;
        maxDownloads: bigint;
        downloadCount: bigint;
        expiresAt: bigint;
        accessCodeHash: string;
        owner: string;
        isActive: boolean;
        hasPassword: boolean;
        contentEncrypted: boolean;
        encryptionKeyHash: string;
        folderId: bigint;
        previewEnabled: boolean;
        previewHash: string;
        anonymousUpload: boolean;
      }
    ],
    "view"
  >;

  folders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        id: bigint;
        owner: string;
        name: string;
        color: string;
        createdAt: bigint;
        fileCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getAccessInfo: TypedContractMethod<
    [fileId: BigNumberish],
    [[boolean, boolean] & { isAuthorized: boolean; hasDownloaded: boolean }],
    "view"
  >;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getEncryptionInfo: TypedContractMethod<
    [fileId: BigNumberish],
    [
      [boolean, boolean] & {
        contentEncrypted: boolean;
        isOwnerOrAuthorized: boolean;
      }
    ],
    "view"
  >;

  getFileExpiry: TypedContractMethod<[fileId: BigNumberish], [bigint], "view">;

  getFileInfo: TypedContractMethod<
    [fileId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean, boolean] & {
        ipfsHash: string;
        createdAt: bigint;
        price: bigint;
        maxDownloads: bigint;
        downloadCount: bigint;
        isActive: boolean;
        hasPassword: boolean;
        contentEncrypted: boolean;
      }
    ],
    "view"
  >;

  getFileMetadata: TypedContractMethod<
    [fileId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean, string] & {
        fileName: string;
        mimeType: string;
        fileSize: bigint;
        expiresAt: bigint;
        folderId: bigint;
        previewEnabled: boolean;
        previewHash: string;
      }
    ],
    "view"
  >;

  getFileOwner: TypedContractMethod<[fileId: BigNumberish], [string], "view">;

  getFilePrivacy: TypedContractMethod<
    [fileId: BigNumberish],
    [[boolean, string] & { anonymousUpload: boolean; visibleOwner: string }],
    "view"
  >;

  getFilesByFolder: TypedContractMethod<
    [folderId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getLatestFileId: TypedContractMethod<[], [bigint], "view">;

  getMyFiles: TypedContractMethod<[], [bigint[]], "view">;

  getMyFolders: TypedContractMethod<[], [bigint[]], "view">;

  getMyWebhooks: TypedContractMethod<[], [bigint[]], "view">;

  getRemainingDownloads: TypedContractMethod<
    [fileId: BigNumberish],
    [bigint],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalFiles: bigint;
        _totalDownloads: bigint;
        _totalVolume: bigint;
        _myFileCount: bigint;
      }
    ],
    "view"
  >;

  isFileExpired: TypedContractMethod<[fileId: BigNumberish], [boolean], "view">;

  moveFileToFolder: TypedContractMethod<
    [fileId: BigNumberish, folderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  reactivateFile: TypedContractMethod<
    [fileId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerWebhook: TypedContractMethod<
    [endpointHash: BytesLike, label: string, eventMask: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestAccess: TypedContractMethod<
    [fileId: BigNumberish, accessCode_: BytesLike],
    [void],
    "payable"
  >;

  revokeAccess: TypedContractMethod<
    [fileId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  totalDownloads: TypedContractMethod<[], [bigint], "view">;

  totalFiles: TypedContractMethod<[], [bigint], "view">;

  totalFolders: TypedContractMethod<[], [bigint], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  totalWebhooks: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateFileMetadata: TypedContractMethod<
    [
      fileId: BigNumberish,
      fileName: string,
      mimeType: string,
      fileSize: BigNumberish,
      previewEnabled: boolean,
      previewHash: string
    ],
    [void],
    "nonpayable"
  >;

  updateFilePrivacy: TypedContractMethod<
    [fileId: BigNumberish, anonymousUpload: boolean],
    [void],
    "nonpayable"
  >;

  updateFileRules: TypedContractMethod<
    [
      fileId: BigNumberish,
      newPrice: BigNumberish,
      newMaxDownloads: BigNumberish,
      newExpiryDays: BigNumberish,
      newAccessCodeHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  updateFolder: TypedContractMethod<
    [folderId: BigNumberish, name: string, color: string, isActive: boolean],
    [void],
    "nonpayable"
  >;

  updateWebhook: TypedContractMethod<
    [
      webhookId: BigNumberish,
      endpointHash: BytesLike,
      label: string,
      eventMask: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;

  uploadFile: TypedContractMethod<
    [
      ipfsHash_: string,
      price_: BigNumberish,
      maxDownloads_: BigNumberish,
      expiryDays_: BigNumberish,
      accessCodeHash_: BytesLike,
      contentEncrypted_: boolean,
      encryptionKeyHash_: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  uploadFileDetailed: TypedContractMethod<
    [input: FhenixDropBox.UploadInputStruct],
    [bigint],
    "nonpayable"
  >;

  uploadFilesBatch: TypedContractMethod<
    [inputs: FhenixDropBox.UploadInputStruct[]],
    [bigint[]],
    "nonpayable"
  >;

  userFiles: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userFolders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userWebhooks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  webhooks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean, bigint] & {
        id: bigint;
        owner: string;
        endpointHash: string;
        label: string;
        eventMask: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  withdrawERC20: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizedUsers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchDownloadFiles"
  ): TypedContractMethod<[fileIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createFolder"
  ): TypedContractMethod<[name: string, color: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateFile"
  ): TypedContractMethod<[fileId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "downloadFile"
  ): TypedContractMethod<[fileId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "downloadHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "files"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean,
        string,
        bigint,
        boolean,
        string,
        boolean
      ] & {
        ipfsHash: string;
        fileName: string;
        mimeType: string;
        fileSize: bigint;
        createdAt: bigint;
        price: bigint;
        maxDownloads: bigint;
        downloadCount: bigint;
        expiresAt: bigint;
        accessCodeHash: string;
        owner: string;
        isActive: boolean;
        hasPassword: boolean;
        contentEncrypted: boolean;
        encryptionKeyHash: string;
        folderId: bigint;
        previewEnabled: boolean;
        previewHash: string;
        anonymousUpload: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "folders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean] & {
        id: bigint;
        owner: string;
        name: string;
        color: string;
        createdAt: bigint;
        fileCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccessInfo"
  ): TypedContractMethod<
    [fileId: BigNumberish],
    [[boolean, boolean] & { isAuthorized: boolean; hasDownloaded: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptionInfo"
  ): TypedContractMethod<
    [fileId: BigNumberish],
    [
      [boolean, boolean] & {
        contentEncrypted: boolean;
        isOwnerOrAuthorized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFileExpiry"
  ): TypedContractMethod<[fileId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFileInfo"
  ): TypedContractMethod<
    [fileId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean, boolean] & {
        ipfsHash: string;
        createdAt: bigint;
        price: bigint;
        maxDownloads: bigint;
        downloadCount: bigint;
        isActive: boolean;
        hasPassword: boolean;
        contentEncrypted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFileMetadata"
  ): TypedContractMethod<
    [fileId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, boolean, string] & {
        fileName: string;
        mimeType: string;
        fileSize: bigint;
        expiresAt: bigint;
        folderId: bigint;
        previewEnabled: boolean;
        previewHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFileOwner"
  ): TypedContractMethod<[fileId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getFilePrivacy"
  ): TypedContractMethod<
    [fileId: BigNumberish],
    [[boolean, string] & { anonymousUpload: boolean; visibleOwner: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFilesByFolder"
  ): TypedContractMethod<[folderId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLatestFileId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyFiles"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMyFolders"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMyWebhooks"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRemainingDownloads"
  ): TypedContractMethod<[fileId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalFiles: bigint;
        _totalDownloads: bigint;
        _totalVolume: bigint;
        _myFileCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFileExpired"
  ): TypedContractMethod<[fileId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "moveFileToFolder"
  ): TypedContractMethod<
    [fileId: BigNumberish, folderId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reactivateFile"
  ): TypedContractMethod<[fileId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerWebhook"
  ): TypedContractMethod<
    [endpointHash: BytesLike, label: string, eventMask: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestAccess"
  ): TypedContractMethod<
    [fileId: BigNumberish, accessCode_: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [fileId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalDownloads"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFiles"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFolders"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWebhooks"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFileMetadata"
  ): TypedContractMethod<
    [
      fileId: BigNumberish,
      fileName: string,
      mimeType: string,
      fileSize: BigNumberish,
      previewEnabled: boolean,
      previewHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateFilePrivacy"
  ): TypedContractMethod<
    [fileId: BigNumberish, anonymousUpload: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateFileRules"
  ): TypedContractMethod<
    [
      fileId: BigNumberish,
      newPrice: BigNumberish,
      newMaxDownloads: BigNumberish,
      newExpiryDays: BigNumberish,
      newAccessCodeHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateFolder"
  ): TypedContractMethod<
    [folderId: BigNumberish, name: string, color: string, isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateWebhook"
  ): TypedContractMethod<
    [
      webhookId: BigNumberish,
      endpointHash: BytesLike,
      label: string,
      eventMask: BigNumberish,
      isActive: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uploadFile"
  ): TypedContractMethod<
    [
      ipfsHash_: string,
      price_: BigNumberish,
      maxDownloads_: BigNumberish,
      expiryDays_: BigNumberish,
      accessCodeHash_: BytesLike,
      contentEncrypted_: boolean,
      encryptionKeyHash_: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uploadFileDetailed"
  ): TypedContractMethod<
    [input: FhenixDropBox.UploadInputStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uploadFilesBatch"
  ): TypedContractMethod<
    [inputs: FhenixDropBox.UploadInputStruct[]],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userFiles"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userFolders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userWebhooks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "webhooks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean, bigint] & {
        id: bigint;
        owner: string;
        endpointHash: string;
        label: string;
        eventMask: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawERC20"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "BatchDownloaded"
  ): TypedContractEvent<
    BatchDownloadedEvent.InputTuple,
    BatchDownloadedEvent.OutputTuple,
    BatchDownloadedEvent.OutputObject
  >;
  getEvent(
    key: "FileAccessed"
  ): TypedContractEvent<
    FileAccessedEvent.InputTuple,
    FileAccessedEvent.OutputTuple,
    FileAccessedEvent.OutputObject
  >;
  getEvent(
    key: "FileDeactivated"
  ): TypedContractEvent<
    FileDeactivatedEvent.InputTuple,
    FileDeactivatedEvent.OutputTuple,
    FileDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "FileDownloaded"
  ): TypedContractEvent<
    FileDownloadedEvent.InputTuple,
    FileDownloadedEvent.OutputTuple,
    FileDownloadedEvent.OutputObject
  >;
  getEvent(
    key: "FileMetadataUpdated"
  ): TypedContractEvent<
    FileMetadataUpdatedEvent.InputTuple,
    FileMetadataUpdatedEvent.OutputTuple,
    FileMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FileMoved"
  ): TypedContractEvent<
    FileMovedEvent.InputTuple,
    FileMovedEvent.OutputTuple,
    FileMovedEvent.OutputObject
  >;
  getEvent(
    key: "FilePrivacyUpdated"
  ): TypedContractEvent<
    FilePrivacyUpdatedEvent.InputTuple,
    FilePrivacyUpdatedEvent.OutputTuple,
    FilePrivacyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FileReactivated"
  ): TypedContractEvent<
    FileReactivatedEvent.InputTuple,
    FileReactivatedEvent.OutputTuple,
    FileReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "FileRulesUpdated"
  ): TypedContractEvent<
    FileRulesUpdatedEvent.InputTuple,
    FileRulesUpdatedEvent.OutputTuple,
    FileRulesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FileUploaded"
  ): TypedContractEvent<
    FileUploadedEvent.InputTuple,
    FileUploadedEvent.OutputTuple,
    FileUploadedEvent.OutputObject
  >;
  getEvent(
    key: "FolderCreated"
  ): TypedContractEvent<
    FolderCreatedEvent.InputTuple,
    FolderCreatedEvent.OutputTuple,
    FolderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FolderUpdated"
  ): TypedContractEvent<
    FolderUpdatedEvent.InputTuple,
    FolderUpdatedEvent.OutputTuple,
    FolderUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WebhookRegistered"
  ): TypedContractEvent<
    WebhookRegisteredEvent.InputTuple,
    WebhookRegisteredEvent.OutputTuple,
    WebhookRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "WebhookUpdated"
  ): TypedContractEvent<
    WebhookUpdatedEvent.InputTuple,
    WebhookUpdatedEvent.OutputTuple,
    WebhookUpdatedEvent.OutputObject
  >;

  filters: {
    "AccessRevoked(uint256,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "BatchDownloaded(address,uint256[])": TypedContractEvent<
      BatchDownloadedEvent.InputTuple,
      BatchDownloadedEvent.OutputTuple,
      BatchDownloadedEvent.OutputObject
    >;
    BatchDownloaded: TypedContractEvent<
      BatchDownloadedEvent.InputTuple,
      BatchDownloadedEvent.OutputTuple,
      BatchDownloadedEvent.OutputObject
    >;

    "FileAccessed(uint256,address,uint256)": TypedContractEvent<
      FileAccessedEvent.InputTuple,
      FileAccessedEvent.OutputTuple,
      FileAccessedEvent.OutputObject
    >;
    FileAccessed: TypedContractEvent<
      FileAccessedEvent.InputTuple,
      FileAccessedEvent.OutputTuple,
      FileAccessedEvent.OutputObject
    >;

    "FileDeactivated(uint256)": TypedContractEvent<
      FileDeactivatedEvent.InputTuple,
      FileDeactivatedEvent.OutputTuple,
      FileDeactivatedEvent.OutputObject
    >;
    FileDeactivated: TypedContractEvent<
      FileDeactivatedEvent.InputTuple,
      FileDeactivatedEvent.OutputTuple,
      FileDeactivatedEvent.OutputObject
    >;

    "FileDownloaded(uint256,address,address)": TypedContractEvent<
      FileDownloadedEvent.InputTuple,
      FileDownloadedEvent.OutputTuple,
      FileDownloadedEvent.OutputObject
    >;
    FileDownloaded: TypedContractEvent<
      FileDownloadedEvent.InputTuple,
      FileDownloadedEvent.OutputTuple,
      FileDownloadedEvent.OutputObject
    >;

    "FileMetadataUpdated(uint256,string,string,uint256,string)": TypedContractEvent<
      FileMetadataUpdatedEvent.InputTuple,
      FileMetadataUpdatedEvent.OutputTuple,
      FileMetadataUpdatedEvent.OutputObject
    >;
    FileMetadataUpdated: TypedContractEvent<
      FileMetadataUpdatedEvent.InputTuple,
      FileMetadataUpdatedEvent.OutputTuple,
      FileMetadataUpdatedEvent.OutputObject
    >;

    "FileMoved(uint256,uint256,uint256)": TypedContractEvent<
      FileMovedEvent.InputTuple,
      FileMovedEvent.OutputTuple,
      FileMovedEvent.OutputObject
    >;
    FileMoved: TypedContractEvent<
      FileMovedEvent.InputTuple,
      FileMovedEvent.OutputTuple,
      FileMovedEvent.OutputObject
    >;

    "FilePrivacyUpdated(uint256,bool)": TypedContractEvent<
      FilePrivacyUpdatedEvent.InputTuple,
      FilePrivacyUpdatedEvent.OutputTuple,
      FilePrivacyUpdatedEvent.OutputObject
    >;
    FilePrivacyUpdated: TypedContractEvent<
      FilePrivacyUpdatedEvent.InputTuple,
      FilePrivacyUpdatedEvent.OutputTuple,
      FilePrivacyUpdatedEvent.OutputObject
    >;

    "FileReactivated(uint256)": TypedContractEvent<
      FileReactivatedEvent.InputTuple,
      FileReactivatedEvent.OutputTuple,
      FileReactivatedEvent.OutputObject
    >;
    FileReactivated: TypedContractEvent<
      FileReactivatedEvent.InputTuple,
      FileReactivatedEvent.OutputTuple,
      FileReactivatedEvent.OutputObject
    >;

    "FileRulesUpdated(uint256,uint256,uint256,uint256,bool)": TypedContractEvent<
      FileRulesUpdatedEvent.InputTuple,
      FileRulesUpdatedEvent.OutputTuple,
      FileRulesUpdatedEvent.OutputObject
    >;
    FileRulesUpdated: TypedContractEvent<
      FileRulesUpdatedEvent.InputTuple,
      FileRulesUpdatedEvent.OutputTuple,
      FileRulesUpdatedEvent.OutputObject
    >;

    "FileUploaded(uint256,address,string,string,uint256,uint256,bool,bool,string,bool)": TypedContractEvent<
      FileUploadedEvent.InputTuple,
      FileUploadedEvent.OutputTuple,
      FileUploadedEvent.OutputObject
    >;
    FileUploaded: TypedContractEvent<
      FileUploadedEvent.InputTuple,
      FileUploadedEvent.OutputTuple,
      FileUploadedEvent.OutputObject
    >;

    "FolderCreated(uint256,address,string,string)": TypedContractEvent<
      FolderCreatedEvent.InputTuple,
      FolderCreatedEvent.OutputTuple,
      FolderCreatedEvent.OutputObject
    >;
    FolderCreated: TypedContractEvent<
      FolderCreatedEvent.InputTuple,
      FolderCreatedEvent.OutputTuple,
      FolderCreatedEvent.OutputObject
    >;

    "FolderUpdated(uint256,string,string,bool)": TypedContractEvent<
      FolderUpdatedEvent.InputTuple,
      FolderUpdatedEvent.OutputTuple,
      FolderUpdatedEvent.OutputObject
    >;
    FolderUpdated: TypedContractEvent<
      FolderUpdatedEvent.InputTuple,
      FolderUpdatedEvent.OutputTuple,
      FolderUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WebhookRegistered(uint256,address,bytes32,uint8)": TypedContractEvent<
      WebhookRegisteredEvent.InputTuple,
      WebhookRegisteredEvent.OutputTuple,
      WebhookRegisteredEvent.OutputObject
    >;
    WebhookRegistered: TypedContractEvent<
      WebhookRegisteredEvent.InputTuple,
      WebhookRegisteredEvent.OutputTuple,
      WebhookRegisteredEvent.OutputObject
    >;

    "WebhookUpdated(uint256,bytes32,uint8,bool)": TypedContractEvent<
      WebhookUpdatedEvent.InputTuple,
      WebhookUpdatedEvent.OutputTuple,
      WebhookUpdatedEvent.OutputObject
    >;
    WebhookUpdated: TypedContractEvent<
      WebhookUpdatedEvent.InputTuple,
      WebhookUpdatedEvent.OutputTuple,
      WebhookUpdatedEvent.OutputObject
    >;
  };
}
