/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FhenixDropBoxInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC_TOKEN"
      | "authorizedUsers"
      | "deactivateFile"
      | "downloadFile"
      | "downloadHistory"
      | "files"
      | "getAccessInfo"
      | "getBalance"
      | "getEncryptionInfo"
      | "getFileExpiry"
      | "getFileInfo"
      | "getFileOwner"
      | "getLatestFileId"
      | "getMyFiles"
      | "getRemainingDownloads"
      | "getStats"
      | "isFileExpired"
      | "owner"
      | "reactivateFile"
      | "renounceOwnership"
      | "requestAccess"
      | "requestAccessERC20"
      | "revokeAccess"
      | "totalDownloads"
      | "totalFiles"
      | "totalVolume"
      | "transferOwnership"
      | "updateFileRules"
      | "uploadFile"
      | "userFiles"
      | "withdraw"
      | "withdrawERC20"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessRevoked"
      | "FileAccessed"
      | "FileDeactivated"
      | "FileDownloaded"
      | "FileReactivated"
      | "FileUploaded"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "USDC_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedUsers",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateFile",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "downloadFile",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "downloadHistory",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "files", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getAccessInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptionInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFileExpiry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFileInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFileOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestFileId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyFiles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingDownloads",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isFileExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactivateFile",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestAccess",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestAccessERC20",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDownloads",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFiles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFileRules",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadFile",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      boolean,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "userFiles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawERC20",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "USDC_TOKEN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateFile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "downloadFile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "downloadHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "files", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccessInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFileExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFileInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFileOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestFileId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMyFiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingDownloads",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isFileExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateFile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAccessERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDownloads",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalFiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFileRules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uploadFile", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userFiles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC20",
    data: BytesLike
  ): Result;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [fileId: BigNumberish, user: AddressLike];
  export type OutputTuple = [fileId: bigint, user: string];
  export interface OutputObject {
    fileId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileAccessedEvent {
  export type InputTuple = [
    fileId: BigNumberish,
    requester: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [fileId: bigint, requester: string, price: bigint];
  export interface OutputObject {
    fileId: bigint;
    requester: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileDeactivatedEvent {
  export type InputTuple = [fileId: BigNumberish];
  export type OutputTuple = [fileId: bigint];
  export interface OutputObject {
    fileId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileDownloadedEvent {
  export type InputTuple = [
    fileId: BigNumberish,
    downloader: AddressLike,
    owner: AddressLike
  ];
  export type OutputTuple = [fileId: bigint, downloader: string, owner: string];
  export interface OutputObject {
    fileId: bigint;
    downloader: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileReactivatedEvent {
  export type InputTuple = [fileId: BigNumberish];
  export type OutputTuple = [fileId: bigint];
  export interface OutputObject {
    fileId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileUploadedEvent {
  export type InputTuple = [
    fileId: BigNumberish,
    owner: AddressLike,
    ipfsHash: string,
    price: BigNumberish,
    hasPassword: boolean,
    contentEncrypted: boolean
  ];
  export type OutputTuple = [
    fileId: bigint,
    owner: string,
    ipfsHash: string,
    price: bigint,
    hasPassword: boolean,
    contentEncrypted: boolean
  ];
  export interface OutputObject {
    fileId: bigint;
    owner: string;
    ipfsHash: string;
    price: bigint;
    hasPassword: boolean;
    contentEncrypted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FhenixDropBox extends BaseContract {
  connect(runner?: ContractRunner | null): FhenixDropBox;
  waitForDeployment(): Promise<this>;

  interface: FhenixDropBoxInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC_TOKEN: TypedContractMethod<[], [string], "view">;

  authorizedUsers: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  deactivateFile: TypedContractMethod<
    [fileId: BigNumberish],
    [void],
    "nonpayable"
  >;

  downloadFile: TypedContractMethod<
    [fileId: BigNumberish],
    [void],
    "nonpayable"
  >;

  downloadHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  files: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean,
        string
      ] & {
        ipfsHash: string;
        createdAt: bigint;
        price: bigint;
        maxDownloads: bigint;
        downloadCount: bigint;
        expiresAt: bigint;
        accessCodeHash: string;
        owner: string;
        isActive: boolean;
        hasPassword: boolean;
        contentEncrypted: boolean;
        encryptionKeyHash: string;
      }
    ],
    "view"
  >;

  getAccessInfo: TypedContractMethod<
    [fileId: BigNumberish],
    [[boolean, boolean] & { isAuthorized: boolean; hasDownloaded: boolean }],
    "view"
  >;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getEncryptionInfo: TypedContractMethod<
    [fileId: BigNumberish],
    [
      [boolean, boolean] & {
        contentEncrypted: boolean;
        isOwnerOrAuthorized: boolean;
      }
    ],
    "view"
  >;

  getFileExpiry: TypedContractMethod<[fileId: BigNumberish], [bigint], "view">;

  getFileInfo: TypedContractMethod<
    [fileId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean, boolean] & {
        ipfsHash: string;
        createdAt: bigint;
        price: bigint;
        maxDownloads: bigint;
        downloadCount: bigint;
        isActive: boolean;
        hasPassword: boolean;
        contentEncrypted: boolean;
      }
    ],
    "view"
  >;

  getFileOwner: TypedContractMethod<[fileId: BigNumberish], [string], "view">;

  getLatestFileId: TypedContractMethod<[], [bigint], "view">;

  getMyFiles: TypedContractMethod<[], [bigint[]], "view">;

  getRemainingDownloads: TypedContractMethod<
    [fileId: BigNumberish],
    [bigint],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalFiles: bigint;
        _totalDownloads: bigint;
        _totalVolume: bigint;
        _myFileCount: bigint;
      }
    ],
    "view"
  >;

  isFileExpired: TypedContractMethod<[fileId: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  reactivateFile: TypedContractMethod<
    [fileId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestAccess: TypedContractMethod<
    [fileId: BigNumberish, accessCode_: BytesLike],
    [void],
    "payable"
  >;

  requestAccessERC20: TypedContractMethod<
    [fileId: BigNumberish, accessCode_: BytesLike, amount_: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [fileId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  totalDownloads: TypedContractMethod<[], [bigint], "view">;

  totalFiles: TypedContractMethod<[], [bigint], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateFileRules: TypedContractMethod<
    [
      fileId: BigNumberish,
      newPrice: BigNumberish,
      newMaxDownloads: BigNumberish,
      newExpiryDays: BigNumberish,
      newAccessCodeHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  uploadFile: TypedContractMethod<
    [
      ipfsHash_: string,
      price_: BigNumberish,
      maxDownloads_: BigNumberish,
      expiryDays_: BigNumberish,
      accessCodeHash_: BytesLike,
      contentEncrypted_: boolean,
      encryptionKeyHash_: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  userFiles: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  withdrawERC20: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizedUsers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateFile"
  ): TypedContractMethod<[fileId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "downloadFile"
  ): TypedContractMethod<[fileId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "downloadHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "files"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean,
        string
      ] & {
        ipfsHash: string;
        createdAt: bigint;
        price: bigint;
        maxDownloads: bigint;
        downloadCount: bigint;
        expiresAt: bigint;
        accessCodeHash: string;
        owner: string;
        isActive: boolean;
        hasPassword: boolean;
        contentEncrypted: boolean;
        encryptionKeyHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccessInfo"
  ): TypedContractMethod<
    [fileId: BigNumberish],
    [[boolean, boolean] & { isAuthorized: boolean; hasDownloaded: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptionInfo"
  ): TypedContractMethod<
    [fileId: BigNumberish],
    [
      [boolean, boolean] & {
        contentEncrypted: boolean;
        isOwnerOrAuthorized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFileExpiry"
  ): TypedContractMethod<[fileId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFileInfo"
  ): TypedContractMethod<
    [fileId: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean, boolean] & {
        ipfsHash: string;
        createdAt: bigint;
        price: bigint;
        maxDownloads: bigint;
        downloadCount: bigint;
        isActive: boolean;
        hasPassword: boolean;
        contentEncrypted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFileOwner"
  ): TypedContractMethod<[fileId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getLatestFileId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyFiles"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRemainingDownloads"
  ): TypedContractMethod<[fileId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalFiles: bigint;
        _totalDownloads: bigint;
        _totalVolume: bigint;
        _myFileCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFileExpired"
  ): TypedContractMethod<[fileId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reactivateFile"
  ): TypedContractMethod<[fileId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestAccess"
  ): TypedContractMethod<
    [fileId: BigNumberish, accessCode_: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "requestAccessERC20"
  ): TypedContractMethod<
    [fileId: BigNumberish, accessCode_: BytesLike, amount_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [fileId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalDownloads"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFiles"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFileRules"
  ): TypedContractMethod<
    [
      fileId: BigNumberish,
      newPrice: BigNumberish,
      newMaxDownloads: BigNumberish,
      newExpiryDays: BigNumberish,
      newAccessCodeHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uploadFile"
  ): TypedContractMethod<
    [
      ipfsHash_: string,
      price_: BigNumberish,
      maxDownloads_: BigNumberish,
      expiryDays_: BigNumberish,
      accessCodeHash_: BytesLike,
      contentEncrypted_: boolean,
      encryptionKeyHash_: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userFiles"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawERC20"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "FileAccessed"
  ): TypedContractEvent<
    FileAccessedEvent.InputTuple,
    FileAccessedEvent.OutputTuple,
    FileAccessedEvent.OutputObject
  >;
  getEvent(
    key: "FileDeactivated"
  ): TypedContractEvent<
    FileDeactivatedEvent.InputTuple,
    FileDeactivatedEvent.OutputTuple,
    FileDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "FileDownloaded"
  ): TypedContractEvent<
    FileDownloadedEvent.InputTuple,
    FileDownloadedEvent.OutputTuple,
    FileDownloadedEvent.OutputObject
  >;
  getEvent(
    key: "FileReactivated"
  ): TypedContractEvent<
    FileReactivatedEvent.InputTuple,
    FileReactivatedEvent.OutputTuple,
    FileReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "FileUploaded"
  ): TypedContractEvent<
    FileUploadedEvent.InputTuple,
    FileUploadedEvent.OutputTuple,
    FileUploadedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AccessRevoked(uint256,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "FileAccessed(uint256,address,uint256)": TypedContractEvent<
      FileAccessedEvent.InputTuple,
      FileAccessedEvent.OutputTuple,
      FileAccessedEvent.OutputObject
    >;
    FileAccessed: TypedContractEvent<
      FileAccessedEvent.InputTuple,
      FileAccessedEvent.OutputTuple,
      FileAccessedEvent.OutputObject
    >;

    "FileDeactivated(uint256)": TypedContractEvent<
      FileDeactivatedEvent.InputTuple,
      FileDeactivatedEvent.OutputTuple,
      FileDeactivatedEvent.OutputObject
    >;
    FileDeactivated: TypedContractEvent<
      FileDeactivatedEvent.InputTuple,
      FileDeactivatedEvent.OutputTuple,
      FileDeactivatedEvent.OutputObject
    >;

    "FileDownloaded(uint256,address,address)": TypedContractEvent<
      FileDownloadedEvent.InputTuple,
      FileDownloadedEvent.OutputTuple,
      FileDownloadedEvent.OutputObject
    >;
    FileDownloaded: TypedContractEvent<
      FileDownloadedEvent.InputTuple,
      FileDownloadedEvent.OutputTuple,
      FileDownloadedEvent.OutputObject
    >;

    "FileReactivated(uint256)": TypedContractEvent<
      FileReactivatedEvent.InputTuple,
      FileReactivatedEvent.OutputTuple,
      FileReactivatedEvent.OutputObject
    >;
    FileReactivated: TypedContractEvent<
      FileReactivatedEvent.InputTuple,
      FileReactivatedEvent.OutputTuple,
      FileReactivatedEvent.OutputObject
    >;

    "FileUploaded(uint256,address,string,uint256,bool,bool)": TypedContractEvent<
      FileUploadedEvent.InputTuple,
      FileUploadedEvent.OutputTuple,
      FileUploadedEvent.OutputObject
    >;
    FileUploaded: TypedContractEvent<
      FileUploadedEvent.InputTuple,
      FileUploadedEvent.OutputTuple,
      FileUploadedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
